
require:
  - rubocop-rails


AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  CacheRootDirectory: ./tmp/rubocop/
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'feature', 'scenario', 'let', 'it', 'draw']
  Exclude: 
    - 'config/environments/**/*'
    - 'config/routes.rb'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments
